/**
 * Embeds the webfonts into CSS as data URIs.
 *
 * They cannot be linked: the experience ships as a single self-contained
 * HTML file and is served under a content security policy that blocks every
 * external host, so a font CDN link would silently fall back to a system
 * face — and a fallback face flashing in mid-recording is unusable.
 *
 * Both faces are variable, so one file per family covers every weight.
 * Latin subset only; the brand copy has no need for the extended ranges and
 * they would double the payload.
 *
 *   node scripts/build-fonts.mjs   →   src/styles/fonts.css
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const FACES = [
  {
    family: 'Sora Variable',
    file: '@fontsource-variable/sora/files/sora-latin-wght-normal.woff2',
    weights: '100 800',
  },
  {
    family: 'Manrope Variable',
    file: '@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2',
    weights: '200 800',
  },
]

const blocks = FACES.map(({ family, file, weights }) => {
  const abs = path.join(root, 'node_modules', file)
  const b64 = fs.readFileSync(abs).toString('base64')
  return `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weights};
  /* block, not swap: a fallback face flashing mid-take ruins the recording,
     and with a data URI there is no network wait to swap away from. */
  font-display: block;
  src: url(data:font/woff2;base64,${b64}) format('woff2-variations');
}`
})

const out = `/* GENERATED by scripts/build-fonts.mjs — do not edit by hand. */

${blocks.join('\n\n')}
`

const dest = path.join(root, 'src/styles/fonts.css')
fs.mkdirSync(path.dirname(dest), { recursive: true })
fs.writeFileSync(dest, out)

console.log(`fonts.css  ${(Buffer.byteLength(out) / 1024).toFixed(0)} kB`)
